#let tab(..content) = {
    table(
        columns: (29%, 1fr),
        fill: (col, row) => if calc.even(row) { luma(240) } else { white },
        ..content,
    )
}


= Kleines Wörterbuch Koreanisch - Deutsch

#tab(
    [Taekwondo], [Kunst des Fuß- und Handkampfes],
    [Tae], [stoßen, springen oder mit dem Fuß zerschmettern],
    [Kwon], [Faust bzw. mit der Faust oder Hand schlagen oder zerstören],
    [Do], [der Weg, die Lehre, die Methode],
    [], [],
    [Poomse], [Kunstbewegungsform],
    [Hanbon-kyorugi (Ilbo-taeryon)], [vorgegebene Partnerübung (Ein-Schritt-Kampf)],
    [Dubon-kyorugi (Iebo-taeryon)], [vorgegebene Partnerübung (Zwei-Schritt-Kampf)],
    [Jayu-kyorugi], [Freikampf],
    [Kyokpa], [Bruchtest],
    [Hosinsul], [Selbstverteidigungskunst],
    [], [],
    [Dojang], [Übungsraum, Trainingsraum],
    [Dobok], [Taekwondo-Anzug],
    [Ty], [Gürtel],
    [Sabom], [Meister, Lehrer],
    [Sabomnim], [Großmeister],
    [Kyongle], [Respektbezeugung, Gruß, grüßen],
    [Junbi], [Kommando: „Vorbereitung“],
    [Sijak], [Beginn der Übung/des Kampfes, beginnen],
    [Guman], [Ende der Übung/des Kampfes, aufhören],
    [Olgul], [Gesicht bzw. der ganze Kopf bis zum Schlüsselbein],
    [Momtong], [Rumpf bzw. vom Schlüsselbein bis zum Nabel],
    [Arae], [Unterleib bzw. vom Nabel abwärts],
    [Ap], [vorn],
    [Dwit], [hinten],
    [Yop], [Seite, seitlich],
    [Baro], [gerade, gleichseitig / zurück zur Ausgangsstellung],
    [Bandae], [Gegenteil, seitenverkehrt],
    [Oen], [links],
    [Orun], [rechts],
    [An], [von außen nach innen],
    [Bakkat], [von innen nach außen],
    [Heycho], [Keil],
    [Otgoro], [Kreuz],
)

#tab(
    [Naeryo], [abwärts],
    [Wiro], [aufwärts],
    [Jabi], [Griff, greifen],
    [Chigi], [Schlag],
    [Twio], [im Sprung, gesprungen],
    [Dolla], [umdrehen],
    [Kihap], [Kampfschrei],
    [Dubon], [doppelt, zweimal hintereinander],
    [Goduro], [Unterstützung],
    [Chung], [blau],
    [Hong], [rot],
    [Milo], [Schub, schieben],
    [Sewo], [senkrecht],
    [Opo], [waagerecht],
    [Jebipum], [Schwalbenform],
    [Jeycho], [gedreht],
    [Chirugi], [Stich mit den Fingerspitzen],
    [Bo-jumok], [linke Hand umfasst rechte Faust],
    [Du-jumok], [beide Fäuste],
    [Dwitkumchi], [hinterer Teil der Ferse],
    [Dwitchuk], [unterer Teil der Ferse],
    [Pyojok], [Ziel, auf den Punkt],
    [Danggyo], [heranziehen],
    [Du-bal-dangsang], [zweifacher Fußtritt im Sprung, mit beiden Füßen nacheinander treten],
)

#tab(
    [Mori], [Kopf],
    [Mok], [Hals],
    [Tok], [Kinn],
    [Son], [Hand],
    [Sonmok], [Handgelenk],
    [Sonnal], [Handkante (Kleinfingerseite)],
    [Sonnaldung], [Handkante (Daumenseite)],
    [Sonkut], [Fingerspitzen],
    [Jumok], [Faust \ (Knöchel von Zeige- u. Mittelfinger bei geschlossener Faust)],
)

#tab(
    [Pal], [Arm],
    [Palgup], [Ellbogen],
    [Palmok], [Unterarm],
    [An-palmok], [Innenseite (Speiche)],
    [Bakkat-palmok], [Außenseite (Elle)],
    [Dari], [Bein],
    [Murup], [Knie],
    [Bal], [Fuß],
    [Balbadak], [Fußsohle],
    [Baldung], [Fußspann],
    [Balnal], [Fußkante (Außenseite)],
    [Apchuk], [Fußballen],
)

#tab(
    [Taeguk 1 bis 8 Jang (1. - 8. Form)], [Ursprung allen Seins],
    [Koryo (9. Form)], [alte südostasiatische Dynastie, \ Namenspate für Korea (Ableitung)],
    [Kumgang (10. Form)], [zu fest, um zerbrochen zu werden (Diamant)],
    [Taebaek (11. Form)], [erhabenste und großartigste Berg Koreas - \ Symbol des Landes (heilig)],
    [Pyongwon (12. Form)], [Ebene],
    [Shipjin (13. Form)], [Zehn],
    [Jitae (14. Form)], [Erde],
    [Chonkwon (15. Form)], [Himmel],
    [Hansoo (16. Form)], [Wasser],
    [Ilyo (17. Form)], [Einheit],
    [], [],
    [Hana], [1],
    [Dul], [2],
    [Set], [3],
    [Net], [4],
    [Dasot], [5],
    [Yosot], [6],
    [Ilgob], [7],
    [Yodul], [8],
    [Ahob], [9],
    [Yol], [10],
)

#tab(
    [*Sogi*], [Stellung],
    [Moa-sogi], [geschlossene Stellung],
    [Charyot-sogi], [Achtungsstellung, zehenoffene Stellung],
    [Junbi-sogi], [Vorbereitungsstellung],
    [Pyonhi-sogi], [Ausgangsstellung, zehenoffene Parallelstellung],
    [Naranhi-sogi], [Offene Parallelstellung],
    [Juchum-sogi], [Sitzstellung],
    [Apkubi], [große Vorwärtsstellung],
    [Apsogi], [kleine Vorwärtsstellung, Schrittstellung],
    [Dwitkubi], [Rückwärtsstellung],
    [Bomsogi], [Tigerstelltung, kleine Rückwärtsstellung],
    [Hakdari-sogi], [Kranichbeinstellung],
    [Kkoa-sogi], [Überkreuzstellung],
    [Apkkoa-sogi], [Seitwärtsbewegung (unterstützende Fuß ist vorn)],
    [Dwitkkoa-sogi], [Vorwärtsbewegung (unterstützende Fuß ist hinten)],
)

#tab(
    [*Makki*], [Block, Abwehr],
    [Arae-makki], [Tiefblock],
    [Yop-makki], [Seitblock (nur in Verbindung mit Juchum-sogi o. Dwitkubi)],
    [An-makki], [Innenblock],
    [Bakkat-makki], [Außenblock],
    [Olgul-makki], [Gesichtsblock],
    [Sonnal-makki], [Handkantenblock],
    [Han-sonnal-makki], [Block mit einer Handkante],
    [Heycho-makki], [beidseitiger Schubblock (Keilblock)],
    [Nullo-makki], [Abwärtsblock mit Batangson (Handballen)],
    [Otgoro-makki], [Kreuzabwehr (Block mit gekreuzten Armen)],
    [Otgoro-arae-makki], [Tiefkreuzblock],
    [Otgoro-olgul-makki], [Gesichtskreuzblock],
    [Gawi-makki], [Scherenblock (Arae-makki + Momtong-an-palmok-bakkat-makki)],
    [Goduro-makki], [Abwehr mit Unterstützung],
    [Goduro-arae-makki], [Tiefblock mit Ünterstützung],
    [Goduro-momtong-makki], [Rumpfblock mit Unterstützung],
    [Goduro-olgul-makki], [Gesichtsblock mit Unterstützung],
    [Kumgang-makki], [Blockform, bei der eine Hand Olgul-makki und die andere Arae-yop-makki ausführt],
    [Santul-makki], [Zweiarmblock, kombinierte Oben-/Unten-Abwehr],
)

#tab(
    [*Chagi*], [Tritt, Schlag, Kick],
    [Apchagi], [Vorwärtstritt],
    [Dollyo-chagi], [Drehschlag, Halbkreistritt],
    [Yop-chagi], [Seitwärtstritt],
    [Dwitchagi], [Rückwärtstritt],
    [Dwit-dollyo-chagi (Twio-ligi)], [Rückwärts-Drehschlag],
    [Huryo-chagi], [Peitschenschlag],
    [Milo-chagi], [Schubkick],
    [Naeryo-chagi], [Abwärtstritt],
    [Twio-chagi], [Tritt im Sprung],
    [Gawi-chagi], [Tritt mit beiden Beinen gespreizt (Scherentritt)],
)

#tab(
    [*Chaolligi*], [Fußschwung (gestreckte Bein vorn/seitlich hochschwingen)],
    [Ap-chaolligi], [Vorwärtsbeinschwung],
    [An-chaolligi], [Beinschwung von außen nach innen],
    [Bakkat-chaolligi], [Beinschwung von innen nach außen],
    [Yop-chaollogi], [Seitwärtsschwung],
)

#tab(
    [*Jirugi*], [Fauststoß],
    [Baro-jirugi], [gegenseitiger Fauststoß],
    [Bandae-jirugi], [gleichseitiger Fauststoß],
    [Yop-jirugi], [Seitwärtsstoß],
    [Dollyo-jirugi], [Halbkreisstoß, Drehstoß],
    [Naeryo-jirugi], [Abwärtsstoß],
    [Chi-jirugi], [Aufwärtsstoß],
    [Sewo-jirugi], [Vertikalstoss (senkrecht)],
    [Jechyo-jirugi], [Stoß mit nach oben gedrehter Faust],
)

#tab(
    [*Jumok-Übung*], [],
    [Jumok], [Faust],
    [Bamjumok], [Spitze Faust (Faust mit vorstehendem Mittelfinger-Knöchel)],
    [Pyonjumok], [halb geöffnete Faust (Flachfaust)],
    [Dungjumok], [Faustrücken],
    [Mejumok], [Faustaußenseite],
    [Batangson], [Handballen],
    [Sonnal], [Handaußenkante (Kleinfingerseite)],
    [Sonkut], [Fingerspitzen],
    [Sonnaldung], [Handkante (Daumenseite)],
    [Palgup], [Ellbogen],
    [Kaljabi], [Schlag mit der Handspanne (Zeigefinger-Daumen-Spanne)],
)

